version: '3'
services:
  api:
    image: note-app-api
    container_name: note-app-api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '5480:80'
      - '5443:443'
  db:
    image: postgres:16
    container_name: note-app-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: NoteApp
      POSTGRES_USER: NoteApp0450
      POSTGRES_PASSWORD: 8af^Tz%3#U3%No
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s 
